In [2]:
import datetime
import pandas as po

In [ ]:
ouro={"Descrição":"Ouro 22K",
      "Valor":0.125}

In [3]:
real_port={"Moeda":"Real Português",
           "Governo":"Manuel I de Portugal",
           "Data de Implementação":datetime.datetime(1500,4,22),
           "Fim da Vigência":datetime.datetime(1833,10,7),
           "Símbolo":"R",
           "Taxa de Conversão":{"ouro":1200}
           }
real_bra={"Moeda":"Real Brasileiro",
           "Governo":"D. Pedro II",
           "Data de Implementação":datetime.datetime(1833,10,8),
           "Fim da Vigência":datetime.datetime(1942,10,31),
           "Símbolo":"Rs",
           "Taxa de Conversão":{1200:2500}
           }
cr={"Moeda":"Cruzeiro",
           "Governo":"Getúlio Vargas",
           "Data de Implementação":datetime.datetime(1942,11,1),
           "Fim da Vigência":datetime.datetime(1967,2,12),
           "Símbolo":"Cr$",
            "Taxa de Conversão":{1000:1} # mil-réis corresponde a um cruzeiro
        #    datetime.datetime(1964,11,30)
           #datetime.datetime(1967,2,12)
           }
crN={"Moeda":"Cruzeiro Novo",
           "Governo":"Castelo Branco",
           "Data de Implementação":datetime.datetime(1967,2,13),
           "Fim da Vigência":datetime.datetime(1970,5,14),
           "Símbolo":"NCr$",
           "Taxa de Conversão":{1000:1} # mil cruzeiros corresponde a um cruzeiro novo
           }
cr2={"Moeda":"Cruzeiro",
           "Governo":"Emílio Garrastazu Médici",
           "Data de Implementação":datetime.datetime(1970,5,15),
           "Fim da Vigência":datetime.datetime(1986,2,27),
           "Símbolo":"Cr$",
           "Taxa de Conversão":{1:1} # um cruzeiro novo corresponde a um cruzeiro
        #    datetime.datetime(1984,8,15),
           }
crz={"Moeda":"Cruzado",
           "Governo":"José Sarney",
           "Data de Implementação":datetime.datetime(1986,2,28),
           "Fim da Vigência":datetime.datetime(1989,1,15),
           "Símbolo":"Cz$",
           "Taxa de Conversão":{1000:1} # mil cruzeiros corresponde a um cruzado
           }
crzN={"Moeda":"Cruzado Novo",
           "Governo":"José Sarney",
           "Data de Implementação":datetime.datetime(1989,1,16),
           "Fim da Vigência":datetime.datetime(1990,3,15),
           "Símbolo":"NCz$",
           "Taxa de Conversão":{1000:1} # mil cruzados corresponde a um cruzado novo
           }
cr3={"Moeda":"Cruzeiro",
           "Governo":"Fernando Collor",
           "Data de Implementação":datetime.datetime(1990,3,16),
           "Fim da Vigência":datetime.datetime(1993,7,31),
           "Símbolo":"Cr$",
           "Taxa de Conversão":{1:1} # um cruzado novo corresponde a um cruzeiro
           }
creal={"Moeda":"Cruzeiro Real",
           "Governo":"Itamar Franco",
           "Data de Implementação":datetime.datetime(1993,8,1),
           "Fim da Vigência":datetime.datetime(1994,6,30),
           "Símbolo":"CR$",
           "Taxa de Conversão":{1000:1} # mil cruzeiros corresponde a um cruzeiro real
           }
brl={"Moeda":"Real",
           "Governo":"Itamar Franco",
           "Data de Implementação":datetime.datetime(1994,7,1),
           "Fim da Vigência":"",
           "Símbolo":"R$",
           "Taxa de Conversão":{2750:1} #dois mil setessentos e cinquenta cruzeiros reais corresponde a um real
           }
# Ordem Cronológica das Moedas
ocm=["real_port","real_bra","cr","crN","cr2","crz","crzN","cr3","creal","brl"]

In [4]:
tab=po.DataFrame([real_port,real_bra,cr,crN,cr2,crz,crzN,cr3,creal,brl])
tab.index=ocm
tab['Data de Implementação']=po.to_datetime(tab['Data de Implementação'], errors='coerce')
tab['Fim da Vigência']=po.to_datetime(tab['Fim da Vigência'], errors='coerce')

In [18]:
infl=po.read_csv('20240402030810.csv',sep=';')
in30=po.read_csv("Inflação 1930-1994.csv",sep=";")
in30["Variação Acumulada no Ano"]=in30["Variação Acumulada no Ano"].str.replace(',','.')
in30.index = po.to_datetime(in30.index, format='%B %Y')
infl=infl[1:30]
infl["Data"]=infl.index
infl["Data"]=infl["Data"].str.replace("dezembro",'Dec')
infl.index = po.to_datetime(infl["Data"], format='%b %Y')
infl=infl.drop(columns='Data')
infl=infl.rename(columns={"Variação acumulada no ano durante o Plano Real":"Variação Acumulada no Ano"})
infl=po.concat([in30,infl])
infl["Variação Acumulada no Ano"]=infl["Variação Acumulada no Ano"].astype(float)/100
infl=infl.rename_axis('Data')

In [6]:
def edit_num(num:float,moeda_final:StopAsyncIteration):
    sufixos = ['Milhão','Bilhão','Trilhão','Quadrilhão','Quintilhão','Sextilhão','Octilhão',
                'Nonilhão', 'Decilhão','', 'Mil', 'Milhões de', 'Bilhões de', 'Trilhões de','Quadrilhões de',
               'Quintilhões de','Sextilhões de','Octilhões de', 'Nonilhões de', 'Decilhões de']
    computus=['','Conto de Réis','Contos de Réis']
    if num == 0.0000:
        return 'zero'
    
    magnitude = 9
    while num >= 1000:
        magnitude += 1
        num /= 1000

    if  moeda_final in ('Real Brasileiro','Real Português'):
        if magnitude==11:
            magnitude=9
            if num==1:
                cpt=1
            else:cpt=2
        elif magnitude>11:
            magnitude-=2
            cpt=2
    else:cpt=0
    
    if num==1 and magnitude>10:
        magnitude-=11
        if cpt==2:
            cpt=1

    return '{} {} {}'.format(round(num, 2), sufixos[magnitude],computus[cpt])

In [ ]:
# def converter(moeda_orig:str,valor:float,ano_dest:int):
#     """
#     Parameters:
#         mod_orig: Moeda de Origem.
#         valor   : Quantidade na moeda original.
#         1951: Ano a se converter.
#     """
#     mod_original=tab.query("`Moeda`==@moeda_orig").index[0]

#     if ano_dest<tab['Data de Implementação'].iloc[1].year:
#         moeda_final= tab['Moeda'].iloc[0]
#         cifra= tab['Símbolo'].iloc[0]
#     elif ano_dest>tab['Data de Implementação'].iloc[-1].year:
#         moeda_final= tab['Moeda'].iloc[-1]
#         cifra= tab['Símbolo'].iloc[-1]
#     else:
#         moeda_final= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
#                       (tab['Fim da Vigência'].dt.year >= ano_dest)]['Moeda'].iloc[0]
#         cifra= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
#                       (tab['Fim da Vigência'].dt.year >= ano_dest)]['Símbolo'].iloc[0]
        
#     if tab[tab['Moeda']==moeda_orig]['Fim da Vigência'].iloc[0].year<ano_dest:
#         mod_final=tab.query("`Moeda`==@moeda_final").index[0]
#         mds=ocm[ocm.index(mod_original):ocm.index(mod_final)+1]
#         conv=valor
#         for i in mds:
#             conv=(conv/next(iter(globals()[i]["Taxa de Conversão"])))*\
#             globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))]
#         conv=round(conv,2)
#     elif tab[tab['Moeda']==moeda_orig]['Data de Implementação'].iloc[0].year>ano_dest:
#         mod_final=tab.query("`Moeda`==@moeda_final").index[0]
#         mds=ocm[ocm.index(mod_final):ocm.index(mod_original)+1][::-1][:-1]
#         conv=valor
#         for i in mds:
#             conv=float((conv*next(iter(globals()[i]["Taxa de Conversão"])))*\
#             globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))])
#         conv=round(conv,2)

#     conv_edit=edit_num(conv,moeda_final)

#     print(corr_infl)

#     print(f"A quantia de {valor} unidades de {moeda_orig} corresponderia a {conv_edit} unidades de "
#            f"{moeda_final}({cifra}) em {ano_dest}.")

In [7]:
def inflacao_acumulada(args):
    # Verificar se há pelo menos uma taxa de inflação fornecida
    if len(args) < 1:
        return "Erro: Forneça pelo menos uma taxa de inflação."
    
    # Calculando a inflação acumulada
    inflacao_acumulada = 1
    for taxa_inflacao in args:
        inflacao_acumulada *= (1 + taxa_inflacao)
    
    inflacao_acumulada -= 1
    return inflacao_acumulada

def corr_infl(valor,periodo_in,periodo_dest):
   """
    Parameters:
        valor        : Quantidade na moeda original.
        periodo_in   : Período de que se quer converter.
        periodo_dest : Período para qual se quer converter.
   """
   taxas=tuple(i for _,i in infl.query(str(min(periodo_in,periodo_dest))+"<`Data`<"+\
      str(max(periodo_in,periodo_dest)))["Variação Acumulada no Ano"].items())
   corre=valor
   infl_periodo=inflacao_acumulada(taxas)
   
   if periodo_in> periodo_dest:
      corre=corre/(1+infl_periodo)
   else:
      corre=corre*(1+infl_periodo)

   if periodo_dest>=1994 and periodo_in >=1994:
        print(f'R${valor} em {periodo_in} tem o mesmo poder de compra que R$ {corre} em {periodo_dest}.')
   else:return corre

In [8]:
def converter(moeda_orig:str,valor:float,ano_dest:int,ano_in=None):
    """
    Parameters:
        mod_orig: Moeda de Origem.
        valor   : Quantidade na moeda original.
        ano_dest: Ano a se converter.
    """
    mod_original=tab.query("`Moeda`==@moeda_orig").index[0]
    if not ano_in:
        ano_in=tab.query("`Moeda`==@moeda_orig")['Data de Implementação'].iloc[0].year

    if ano_dest<tab['Data de Implementação'].iloc[1].year:
        moeda_final= tab['Moeda'].iloc[0]
        cifra= tab['Símbolo'].iloc[0]
    elif ano_dest>tab['Data de Implementação'].iloc[-1].year:
        moeda_final= tab['Moeda'].iloc[-1]
        cifra= tab['Símbolo'].iloc[-1]
    else:
        moeda_final= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
                      (tab['Fim da Vigência'].dt.year >= ano_dest)]['Moeda'].iloc[0]
        cifra= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
                      (tab['Fim da Vigência'].dt.year >= ano_dest)]['Símbolo'].iloc[0]
        
    if tab[tab['Moeda']==moeda_orig]['Fim da Vigência'].iloc[0].year<ano_dest:
        mod_final=tab.query("`Moeda`==@moeda_final").index[0]
        mds=ocm[ocm.index(mod_original):ocm.index(mod_final)+1]
        conv=valor
        for i in mds:
            conv=(conv/next(iter(globals()[i]["Taxa de Conversão"])))*\
            globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))]
        conv=round(conv,2)
    elif tab[tab['Moeda']==moeda_orig]['Data de Implementação'].iloc[0].year>ano_dest:
        mod_final=tab.query("`Moeda`==@moeda_final").index[0]
        mds=ocm[ocm.index(mod_final):ocm.index(mod_original)+1][::-1][:-1]
        conv=valor
        for i in mds:
            conv=float((conv*next(iter(globals()[i]["Taxa de Conversão"])))*\
            globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))])
        conv=round(conv,2)

    conv_edit=edit_num(conv,moeda_final)

    print(f"A quantia de {valor} unidades de {moeda_orig} corresponderia a {conv_edit} unidades de "
           f"{moeda_final}({cifra}) em {ano_dest}.")
    
    # return conv
    # print(corr_infl(conv,ano_in,ano_dest))

In [9]:
converter('Real',100,1972)

A quantia de 100 unidades de Real corresponderia a 275.0 Quadrilhões de  unidades de Cruzeiro(Cr$) em 1972.

In [ ]:
corr_infl(7500.85,2023,1995)

## Rascunho

In [25]:
tab

,Moeda,Governo,Data de Implementação,Fim da Vigência,Símbolo,Taxa de Conversão
real_port,Real Português,Manuel I de Portugal,NaT,1833-10-07,R,{'ouro': 1200}
real_bra,Real Brasileiro,D. Pedro II,1833-10-08,1942-10-31,Rs,{1200: 2500}
cr,Cruzeiro,Getúlio Vargas,1942-11-01,1967-02-12,Cr$,{1000: 1}
crN,Cruzeiro Novo,Castelo Branco,1967-02-13,1970-05-14,NCr$,{1000: 1}
cr2,Cruzeiro,Emílio Garrastazu Médici,1970-05-15,1986-02-27,Cr$,{1: 1}
crz,Cruzado,José Sarney,1986-02-28,1989-01-15,Cz$,{1000: 1}
crzN,Cruzado Novo,José Sarney,1989-01-16,1990-03-15,NCz$,{1000: 1}
cr3,Cruzeiro,Fernando Collor,1990-03-16,1993-07-31,Cr$,{1: 1}
creal,Cruzeiro Real,Itamar Franco,1993-08-01,1994-06-30,CR$,{1000: 1}
brl,Real,Itamar Franco,1994-07-01,NaT,R$,{2750: 1}

In [16]:
def converter_test(moeda_orig:str,valor:float,ano_dest:int,ano_in=None):
    """
    Parameters:
        mod_orig: Moeda de Origem.
        valor   : Quantidade na moeda original.
        ano_dest: Ano a se converter.
    """
    mod_original=tab.query("`Moeda`==@moeda_orig").index[0]
    cifra_orig=tab.query("`Moeda`==@moeda_orig")['Símbolo'].iloc[0]
    if not ano_in:
        ano_in=tab.query("`Moeda`==@moeda_orig")['Data de Implementação'].iloc[0].year

    if ano_dest<tab['Data de Implementação'].iloc[1].year:
        moeda_final= tab['Moeda'].iloc[0]
        cifra= tab['Símbolo'].iloc[0]
    elif ano_dest>tab['Data de Implementação'].iloc[-1].year:
        moeda_final= tab['Moeda'].iloc[-1]
        cifra= tab['Símbolo'].iloc[-1]
    else:
        moeda_final= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
                      (tab['Fim da Vigência'].dt.year >= ano_dest)]['Moeda'].iloc[0]
        cifra= tab[(tab['Data de Implementação'].dt.year <= ano_dest) &
                      (tab['Fim da Vigência'].dt.year >= ano_dest)]['Símbolo'].iloc[0]
        
    if tab[tab['Moeda']==moeda_orig]['Fim da Vigência'].iloc[0].year<ano_dest:
        mod_final=tab.query("`Moeda`==@moeda_final").index[0]
        mds=ocm[ocm.index(mod_original):ocm.index(mod_final)+1]
        conv=valor
        for i in mds:
            conv=(conv/next(iter(globals()[i]["Taxa de Conversão"])))*\
            globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))]
        conv=round(conv,2)
    elif tab[tab['Moeda']==moeda_orig]['Data de Implementação'].iloc[0].year>ano_dest:
        mod_final=tab.query("`Moeda`==@moeda_final").index[0]
        mds=ocm[ocm.index(mod_final):ocm.index(mod_original)+1][::-1][:-1]
        conv=valor
        for i in mds:
            conv=float((conv*next(iter(globals()[i]["Taxa de Conversão"])))*\
            globals()[i]["Taxa de Conversão"][next(iter(globals()[i]["Taxa de Conversão"]))])
        conv=round(conv,2)

    conv_edit=edit_num(conv,moeda_final)

    print(f"A quantia de {valor} unidades de {moeda_orig} corresponderia a {conv_edit} unidades de "
           f"{moeda_final}({cifra}) em {ano_dest}.")

    return conv,ano_in,cifra,cifra_orig

In [13]:
def converter_e_corrigir(moeda_orig:str,valor:float,ano_dest:int,ano_in=None):
    
    vlr,ano_in,cfra,cfra_orig=converter_test(moeda_orig,valor,ano_dest,ano_in)

    corre=corr_infl(vlr,ano_in,ano_dest)

    print(f'{cfra_orig} {valor} em {ano_in} tem o mesmo poder de compra que {cfra} {corre} em {ano_dest}.')

In [17]:
converter_e_corrigir('Real',1000,1962)

A quantia de 1000 unidades de Real corresponderia a 2.75 Quintilhões de  unidades de Cruzeiro(Cr$) em 1962.
R$ 1000 em 1994 tem o mesmo poder de compra que Cr$ 634233.0009834298 em 1962.

In [11]:
converter("Real",1500,1855)

A quantia de 1500 unidades de Real corresponderia a 4.12 Quadrilhões de Contos de Réis unidades de Real Brasileiro(Rs) em 1855.

In [108]:
corr_infl(2.75e+18,1994,1962)

634233.0009834298

In [66]:
k=[0.516, 0.799]
inflacao_acumulada(k)

1.727284

In [45]:
infl[20:70]

            Variação Acumulada no Ano
Data
1950-12-01                     0.1240
1951-12-01                     0.1230
1952-12-01                     0.1270
1953-12-01                     0.2060
1954-12-01                     0.2580
1955-12-01                     0.1220
1956-12-01                     0.2450
1957-12-01                     0.0700
1958-12-01                     0.2440
1959-12-01                     0.3940
1960-12-01                     0.3050
1961-12-01                     0.4780
1962-12-01                     0.5160
1963-12-01                     0.7990
1964-12-01                     0.9210
1965-12-01                     0.3430
1966-12-01                     0.3910
1967-12-01                     0.2500
1968-12-01                     0.2540
1969-12-01                     0.1930
1970-12-01                     0.1930
1971-12-01                     0.1950
1972-12-01                     0.1570
1973-12-01                     0.1560
1974-12-01                     0.2690
1975-12-01                     0.2930
1976-12-01                     0.4630
1977-12-01                     0.3880
1978-12-01                     0.4070
1979-12-01                     0.7730
1980-12-01                     1.1020
1981-12-01                     0.9520
1982-12-01                     0.9970
1983-12-01                     2.1100
1984-12-01                     2.2380
1985-12-01                     2.3510
1986-12-01                     0.6500
1987-12-01                     4.1580
1988-12-01                    10.3760
1989-12-01                    17.8290
1990-12-01                    14.7660
1991-12-01                     4.8020
1992-12-01                    11.5800
1993-12-01                    24.7700
1994-12-01                     9.1600
1995-12-01                     0.2241
1996-12-01                     0.0956
1997-12-01                     0.0522
1998-12-01                     0.0165
1999-12-01                     0.0894